### ISSUE TITLE
Dice Roll upgrades

### ISSUE THREAD

**Issue by crazybmanp** [crazybmanp/RyuZU-Bot#18]
- [x] Make default behavior 1d6
- [x] Sum up dice
- [x] Multiple kinds of dice

**Comment by razage** [comment]
probably covered by multiple kinds of dice, but having modifiers might be nice since you're going to all this trouble anyway. like 2d6+6.

**Comment by crazybmanp** [comment]
sadly, the way i am doing it i won't be able to support +[const] but everything else works.
