### ISSUE TITLE
Bot info command

### ISSUE THREAD

**Issue by razage** [crazybmanp/RyuZU-Bot#25]
I suppose it doesn't really add much functionality, but I thought it would be good to have a command that gives a version number or something. We could even do something like Ayana's =info command if we really wanted to go crazy.

**Comment by crazybmanp** [comment]
yea might be useful.
we should make a list of what info it should contain

i suppose to start (this should be sumarized in the OP)

- name
- description
- version
- developers (major contributors)
- contributors
- github link

**Comment by razage** [comment]
I've implemented the skeleton of this command, but we need to discuss a couple points.
* What color should it be? Right now it's our standard magenta.
* Are there more fields we want?
* Run the command. Is the developers field too long? Or should it just not be inline?
* Should the name of the bot change based on what bot is running it? Or should it always be RyuZU-Bot since that's the "software" it would be running?

Also this will need to be slightly edited once the versioning system is in place.

**Comment by crazybmanp** [comment]
i suppose to solve 2 and 4) RyuZU-bot should be a seperate identifier than what the bot's name is.
1) ¯\_(ツ)_/¯
2) other than that ¯\_(ツ)_/¯
3) maybe make that a vertical list? (not sure)
Other note) contributors may need to be stored in an outside json file, maybe we should do this with the devs too.

**Comment by crazybmanp** [comment]
i guess as for color, magenta is striking, and already implemented

**Comment by razage** [comment]
I think moving it to json would be fine. But it will be easily editable, not that it isn't already. In case you didn't look at the color definition, it's very easy to change and the branch isn't merged in yet. 
![image](https://cloud.githubusercontent.com/assets/9331220/24934226/318ee16e-1ecf-11e7-976d-4d68f6289464.png)
This is the format possibilities we're given. I can't lay it out any differently than that. Fields can be more "vertical" though by just not making them inline.

**Comment by razage** [comment]
also contributors might become problematic if we ever got to the point there were many contributors. it probably will have to be on its own line.

**Comment by crazybmanp** [comment]
i was hoping for a way to vertically display them. in this case, maybe we should just not have them included here.

**Comment by razage** [comment]
If the need arises, maybe we should have a contributors command (or subcommand) that just spits out a list of them. Otherwise I guess the info command works as desired.
